/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"wwwin-github.cisco.com/eti/fledge/pkg/objects"
	"wwwin-github.cisco.com/eti/fledge/pkg/util"
)

type AppInfo struct {
	controllerInfo objects.ServerInfo
}

func CreateURI(endPoint string, uriMap map[string]string) string {
	return util.CreateURI(App.controllerInfo.IP, util.ControllerRestApiPort, endPoint, uriMap)
}
