apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-configmap
  namespace: '{{ .Release.Namespace }}'
data:
  controller.yaml: |
    ---
    brokers:
      - sort: {{ .Values.broker.sort }}
        host: {{ .Values.broker.host }}
    db: {{ .Values.database.uri }}
    notifier: {{ .Values.servicename }}-notifier:{{ .Values.componentPorts.notifier }}
    platform: k8s
    registry:
      sort: {{ .Values.registry.sort }}
      uri: {{ .Values.registry.uri }}
