apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-configmap
  namespace: '{{ .Release.Namespace }}'
data:
  controller.yaml: |
    ---
    brokers:
      - sort: mqtt
        host: mqtt.eclipseprojects.io
    db: {{ .Values.database.uri }}
    notifier: {{ .Values.servicename }}-notifier:{{ .Values.componentPorts.notifier }}
    platform: k8s
    registry:
      sort: mlflow
      uri: http://mlflow:5000
