apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-configmap
  namespace: '{{ .Release.Namespace }}'
data:
  controller.yaml: |
    ---
    db: {{ .Values.database.uri }}
    notifier: {{ .Values.servicename }}-notifier:{{ .Values.componentPorts.notifier }}
    platform: k8s
    jobParams:
      image: {{ .Values.workerImage.preamble }}{{ .Values.workerImage.name }}:{{ .Values.workerImage.tag }}
      brokers:
        - sort: {{ .Values.broker.sort }}
          host: {{ .Values.broker.host }}
      registry:
        sort: {{ .Values.registry.sort }}
        uri: {{ .Values.registry.uri }}
