apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-configmap
  namespace: '{{ .Release.Namespace }}'
data:
  controller.yaml: |
    ---
    db: mongodb://fledge-db:27017
    brokers:
      - sort: mqtt
        host: mqtt.eclipseprojects.io
    notifier: fledge-notifier:10101
    platform: k8s
    registry: http://mlflow:5000
