apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-apiserver
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}-apiserver
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}-apiserver
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "{{ .Values.metricsPort }}"
      #   prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: {{ .Values.servicename }}-apiserver
        image: "{{ .Values.docker.GeneralFullImagePreamble }}{{ .Values.dimage }}:{{ .Values.tagversion }}"
        command: ["/usr/bin/apiserver"]
        args:
          - "--controller"
          - "http://{{ .Values.servicename }}-controller:{{ .Values.componentPorts.controller }}"
        ports:
        - containerPort: {{ .Values.componentPorts.apiserver }}

      {{- if .Values.mongodbcredentials }}
      volumes:
        - name: {{ .Release.Name }}-mongodb
          secret:
            secretName: {{ .Release.Name }}-mongodb
      {{- end }}
