apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-controller
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}-controller
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}-controller
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "{{ .Values.metricsPort }}"
      #   prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: controller
      imagePullSecrets:
      - name: ecr-pull-secret
      containers:
      - name: {{ .Values.servicename }}-controller
        image: "{{ .Values.docker.GeneralFullImagePreamble }}{{ .Values.dimage }}:{{ .Values.tagversion }}"
        command: ["/usr/bin/controller"]
        args:
          - "--db"
          - "{{ .Values.database.uri }}"
          - "--notifier"
          - "{{ .Values.servicename }}-notifier:{{ .Values.componentPorts.notifier }}"
        ports:
        - containerPort: {{ .Values.componentPorts.controller }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
        {{- if .Values.mongodbcredentials }}
        volumes:
          - name: {{ .Release.Name }}-mongodb
            secret:
              secretName: {{ .Release.Name }}-mongodb
        {{- end }}
