{{- if .Values.mongodbcredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  MONGODB_PASSWORD  : {{.Values.mongodbcredentials.password | b64enc}}
{{- end }}
