/*
 * Job REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

type JobInfoTimestamp struct {
	CreatedAt int64 `bson:"created_at" json:"created_at,omitempty"`

	StartedAt int64 `bson:"started_at" json:"started_at,omitempty"`

	UpdatedAt int64 `bson:"updated_at" json:"updated_at,omitempty"`

	CompletedAt int64 `bson:"completed_at" json:"completed_at,omitempty"`
}
