/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

// DesignSchemas - A collection of design schemas related to design template
type DesignSchemas struct {
	Schemas []DesignSchema `json:"schemas"`
}
