/*
 * Job REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

// JobNodes - Node information for the job.
// TODO remove me after prototyping phase is done.
type JobNodes struct {
	DesignId string `json:"designId,omitempty"`

	Nodes []ServerInfo `json:"nodes,omitempty"`
}
