/*
 * Job REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

// JobInfo - Basic job information.
type JobInfo struct {
	ID string `bson:"_id,omitempty" json:"id,omitempty"`

	UserId string `bson:"userId" json:"userId,omitempty"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	DesignId string `bson:"designId" json:"designId"`

	Priority string `json:"priority,omitempty"`

	Status string `json:"status,omitempty"`

	Timestamp JobInfoTimestamp `json:"timestamp,omitempty"`

	Dataset map[string]interface{} `json:"dataset,omitempty"`

	CodeBlock map[string]interface{} `json:"codeBlock,omitempty"`

	Config map[string]interface{} `json:"config,omitempty"`
}
