/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

// Error - Generic error object.
type Error struct {
	Code int32 `json:"code"`

	Message string `json:"message"`
}
