/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

// DesignSchema - Schema to define the roles and their connections
type DesignSchema struct {
	ID string `bson:"_id,omitempty" json:"id,omitempty"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Roles []Role `bson:"roles" json:"roles"`

	Channels []Channel `json:"channels"`

	Connectors []Connector `json:"connectors,omitempty"`
}
