/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package objects

import "go.mongodb.org/mongo-driver/bson/primitive"

// Design - Design template details along with all the schemas.
type Design struct {
	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	ID primitive.ObjectID `bson:"_id,omitempty" json:"id,omitempty"`

	UserId string `bson:"userId,omitempty" json:"userId,omitempty"`

	Schemas []DesignSchema `json:"schemas"`
}
