/*
 * Job REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"

	"go.uber.org/zap"
	"wwwin-github.cisco.com/eti/fledge/pkg/objects"
)

// DevApiService is a service that implents the logic for the DevApiServicer
// This service should implement the business logic for every endpoint for the DevApi API.
// Include any external packages or services that will be required by this service.
type DevApiService struct {
}

// NewDevApiService creates a default api service
func NewDevApiService() DevApiServicer {
	return &DevApiService{}
}

var JobNodesInMem = make(map[string]objects.JobNodes)

// JobNodes - Nodes information for the job
func (s *DevApiService) JobNodes(ctx context.Context, user string, jobNodes objects.JobNodes) (ImplResponse, error) {
	zap.S().Infof("Adding nodes for designId : %s", jobNodes.DesignId)
	JobNodesInMem[jobNodes.DesignId] = jobNodes
	return Response(http.StatusCreated, nil), nil
}
