/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"os"
)

// AgentApiRouter defines the required methods for binding the api requests to a responses for the AgentApi
// The AgentApiRouter implementation should parse necessary information from the http request,
// pass the data to a AgentApiServicer to perform the required actions, then write the service results to the http response.
type AgentApiRouter interface {
	UpdateAgentStatus(http.ResponseWriter, *http.Request)
}

// DatasetsApiRouter defines the required methods for binding the api requests to a responses for the DatasetsApi
// The DatasetsApiRouter implementation should parse necessary information from the http request,
// pass the data to a DatasetsApiServicer to perform the required actions, then write the service results to the http response.
type DatasetsApiRouter interface {
	CreateDataset(http.ResponseWriter, *http.Request)
	GetAllDatasets(http.ResponseWriter, *http.Request)
	GetDataset(http.ResponseWriter, *http.Request)
	GetDatasets(http.ResponseWriter, *http.Request)
	UpdateDataset(http.ResponseWriter, *http.Request)
}

// DesignCodesApiRouter defines the required methods for binding the api requests to a responses for the DesignCodesApi
// The DesignCodesApiRouter implementation should parse necessary information from the http request,
// pass the data to a DesignCodesApiServicer to perform the required actions, then write the service results to the http response.
type DesignCodesApiRouter interface {
	CreateDesignCode(http.ResponseWriter, *http.Request)
	GetDesignCode(http.ResponseWriter, *http.Request)
	UpdateDesignCode(http.ResponseWriter, *http.Request)
}

// DesignSchemasApiRouter defines the required methods for binding the api requests to a responses for the DesignSchemasApi
// The DesignSchemasApiRouter implementation should parse necessary information from the http request,
// pass the data to a DesignSchemasApiServicer to perform the required actions, then write the service results to the http response.
type DesignSchemasApiRouter interface {
	CreateDesignSchema(http.ResponseWriter, *http.Request)
	GetDesignSchema(http.ResponseWriter, *http.Request)
	GetDesignSchemas(http.ResponseWriter, *http.Request)
	UpdateDesignSchema(http.ResponseWriter, *http.Request)
}

// DesignsApiRouter defines the required methods for binding the api requests to a responses for the DesignsApi
// The DesignsApiRouter implementation should parse necessary information from the http request,
// pass the data to a DesignsApiServicer to perform the required actions, then write the service results to the http response.
type DesignsApiRouter interface {
	CreateDesign(http.ResponseWriter, *http.Request)
	GetDesign(http.ResponseWriter, *http.Request)
	GetDesigns(http.ResponseWriter, *http.Request)
}

// DevApiRouter defines the required methods for binding the api requests to a responses for the DevApi
// The DevApiRouter implementation should parse necessary information from the http request,
// pass the data to a DevApiServicer to perform the required actions, then write the service results to the http response.
type DevApiRouter interface {
	JobNodes(http.ResponseWriter, *http.Request)
	UpdateJobNodes(http.ResponseWriter, *http.Request)
}

// JobsApiRouter defines the required methods for binding the api requests to a responses for the JobsApi
// The JobsApiRouter implementation should parse necessary information from the http request,
// pass the data to a JobsApiServicer to perform the required actions, then write the service results to the http response.
type JobsApiRouter interface {
	ChangeJobSchema(http.ResponseWriter, *http.Request)
	CreateJob(http.ResponseWriter, *http.Request)
	DeleteJob(http.ResponseWriter, *http.Request)
	GetJob(http.ResponseWriter, *http.Request)
	GetJobStatus(http.ResponseWriter, *http.Request)
	GetJobsStatus(http.ResponseWriter, *http.Request)
	UpdateJob(http.ResponseWriter, *http.Request)
	UpdateJobStatus(http.ResponseWriter, *http.Request)
}

// AgentApiServicer defines the api actions for the AgentApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AgentApiServicer interface {
	UpdateAgentStatus(context.Context, string, string, string, AgentStatus) (ImplResponse, error)
}

// DatasetsApiServicer defines the api actions for the DatasetsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DatasetsApiServicer interface {
	CreateDataset(context.Context, string, DatasetInfo) (ImplResponse, error)
	GetAllDatasets(context.Context, int32) (ImplResponse, error)
	GetDataset(context.Context, string, string) (ImplResponse, error)
	GetDatasets(context.Context, string, int32) (ImplResponse, error)
	UpdateDataset(context.Context, string, string, DatasetInfo) (ImplResponse, error)
}

// DesignCodesApiServicer defines the api actions for the DesignCodesApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DesignCodesApiServicer interface {
	CreateDesignCode(context.Context, string, string, string, string, *os.File) (ImplResponse, error)
	GetDesignCode(context.Context, string, string, string) (ImplResponse, error)
	UpdateDesignCode(context.Context, string, string, string, string, string, *os.File) (ImplResponse, error)
}

// DesignSchemasApiServicer defines the api actions for the DesignSchemasApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DesignSchemasApiServicer interface {
	CreateDesignSchema(context.Context, string, string, DesignSchema) (ImplResponse, error)
	GetDesignSchema(context.Context, string, string, string) (ImplResponse, error)
	GetDesignSchemas(context.Context, string, string) (ImplResponse, error)
	UpdateDesignSchema(context.Context, string, string, string, DesignSchema) (ImplResponse, error)
}

// DesignsApiServicer defines the api actions for the DesignsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DesignsApiServicer interface {
	CreateDesign(context.Context, string, DesignInfo) (ImplResponse, error)
	GetDesign(context.Context, string, string) (ImplResponse, error)
	GetDesigns(context.Context, string, int32) (ImplResponse, error)
}

// DevApiServicer defines the api actions for the DevApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DevApiServicer interface {
	JobNodes(context.Context, string, JobNodes) (ImplResponse, error)
	UpdateJobNodes(context.Context, string, JobNodes) (ImplResponse, error)
}

// JobsApiServicer defines the api actions for the JobsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type JobsApiServicer interface {
	ChangeJobSchema(context.Context, string, string, string, string) (ImplResponse, error)
	CreateJob(context.Context, string, JobSpec) (ImplResponse, error)
	DeleteJob(context.Context, string, string) (ImplResponse, error)
	GetJob(context.Context, string, string) (ImplResponse, error)
	GetJobStatus(context.Context, string, string) (ImplResponse, error)
	GetJobsStatus(context.Context, string, int32) (ImplResponse, error)
	UpdateJob(context.Context, string, string, JobSpec) (ImplResponse, error)
	UpdateJobStatus(context.Context, string, string, JobStatus) (ImplResponse, error)
}
