/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AgentStatus - agent status object.
type AgentStatus struct {
	UpdateType string `json:"updateType"`

	Status string `json:"status"`

	Message string `json:"message"`
}
