/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type JobPriority string

// List of JobPriority
const (
	LOW    JobPriority = "low"
	MEDIUM JobPriority = "medium"
	HIGH   JobPriority = "high"
)
