/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Role - Define the role of a compute unit
type Role struct {
	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	IsDataConsumer bool `json:"isDataConsumer,omitempty"`

	Replica int32 `json:"replica,omitempty"`
}
