/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CommBackend string

// List of CommBackend
const (
	MQTT CommBackend = "mqtt"
	P2P  CommBackend = "p2p"
)
