// Copyright (c) 2022 Cisco Systems, Inc. and its affiliates
// All rights reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TaskType string

// List of TaskType
const (
	USER   TaskType = "user"
	SYSTEM TaskType = "system"
)

// AssertTaskTypeRequired checks if the required fields are not zero-ed
func AssertTaskTypeRequired(obj TaskType) error {
	return nil
}

// AssertRecurseTaskTypeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TaskType (e.g. [][]TaskType), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTaskTypeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTaskType, ok := obj.(TaskType)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTaskTypeRequired(aTaskType)
	})
}
