/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// JobSpec - Job specification
type JobSpec struct {
	Id string `json:"id,omitempty"`

	UserId string `json:"userId"`

	DesignId string `json:"designId"`

	SchemaVersion string `json:"schemaVersion"`

	CodeVersion string `json:"codeVersion"`

	DatasetIds []string `json:"datasetIds,omitempty"`

	Priority string `json:"priority,omitempty"`

	Backend string `json:"backend,omitempty"`

	MaxRunTime int32 `json:"maxRunTime,omitempty"`

	InitialModelId string `json:"initialModelId,omitempty"`

	Hyperparameters []map[string]interface{} `json:"hyperparameters,omitempty"`

	Dependencies []string `json:"dependencies,omitempty"`
}
