// Copyright 2022 Cisco Systems, Inc. and its affiliates
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

/*
 * Flame REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// JobSpec - Job specification
type JobSpec struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	UserId string `json:"userId,omitempty"`

	DesignId string `json:"designId"`

	SchemaRevision int32 `json:"schemaRevision,omitempty"`

	CodeRevision int32 `json:"codeRevision,omitempty"`

	Priority JobPriority `json:"priority,omitempty"`

	Backend CommBackend `json:"backend"`

	MaxRunTime int32 `json:"maxRunTime,omitempty"`

	// Dataset specification
	DataSpec []RoleDatasetGroups `json:"dataSpec,omitempty"`

	ModelSpec ModelSpec `json:"modelSpec,omitempty"`
}

// AssertJobSpecRequired checks if the required fields are not zero-ed
func AssertJobSpecRequired(obj JobSpec) error {
	elements := map[string]interface{}{
		"name":     obj.Name,
		"designId": obj.DesignId,
		"backend":  obj.Backend,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.DataSpec {
		if err := AssertRoleDatasetGroupsRequired(el); err != nil {
			return err
		}
	}
	if err := AssertModelSpecRequired(obj.ModelSpec); err != nil {
		return err
	}
	return nil
}

// AssertJobSpecConstraints checks if the values respects the defined constraints
func AssertJobSpecConstraints(obj JobSpec) error {
	return nil
}
