/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Design - Design template details along with all the schemas.
type Design struct {
	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Id string `json:"id"`

	UserId string `json:"userId,omitempty"`

	Schemas []DesignSchema `json:"schemas"`
}
