/*
 * Job REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"context"
	"fmt"
	"net/http"

	"go.uber.org/zap"

	"wwwin-github.cisco.com/eti/fledge/pkg/openapi"
	"wwwin-github.cisco.com/eti/fledge/pkg/restapi"
	"wwwin-github.cisco.com/eti/fledge/pkg/util"
)

// JobApiService is a service that implents the logic for the JobApiServicer
// This service should implement the business logic for every endpoint for the JobApi API.
// Include any external packages or services that will be required by this service.
type JobApiService struct {
}

// NewJobApiService creates a default api service
func NewJobApiService() openapi.JobApiServicer {
	return &JobApiService{}
}

// DeleteJob - Delete job by id.
func (s *JobApiService) DeleteJob(ctx context.Context, user string, jobId string) (openapi.ImplResponse, error) {
	// TODO - update DeleteJob with the required logic for this service method.
	// Add api_job_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation
	// when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	//return Response(401, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return openapi.Response(http.StatusNotImplemented, nil), fmt.Errorf("DeleteJob method not implemented")
}

// GetJob - Get job detail.
func (s *JobApiService) GetJob(ctx context.Context, user string, jobId string) (openapi.ImplResponse, error) {
	//TODO - validate the input
	zap.S().Debugf("Get job details received for user: %s | jobId: %v", user, jobId)

	//create controller request
	uriMap := map[string]string{
		"user":  user,
		"jobId": jobId,
	}
	url := restapi.CreateURL(Host, Port, restapi.GetJobEndPoint, uriMap)

	//send get request
	code, responseBody, err := restapi.HTTPGet(url)

	//response to the user
	if err != nil {
		return openapi.Response(http.StatusInternalServerError, nil), fmt.Errorf("get job details request failed")
	}

	if err = restapi.CheckStatusCode(code); err != nil {
		return openapi.Response(code, nil), err
	}

	resp := openapi.JobInfo{}
	err = util.ByteToStruct(responseBody, &resp)
	return openapi.Response(http.StatusOK, resp), err
}

// SubmitJob - Submit a new job.
func (s *JobApiService) SubmitJob(ctx context.Context, user string, jobInfo openapi.JobInfo) (openapi.ImplResponse, error) {
	//TODO - validate the input
	zap.S().Debugf("New job request received for user: %s | jobInfo: %v", user, jobInfo)

	//create controller request
	jobInfo.UserId = user
	uriMap := map[string]string{
		"user": user,
	}
	url := restapi.CreateURL(Host, Port, restapi.SubmitJobEndPoint, uriMap)

	//send post request
	code, responseBody, err := restapi.HTTPPost(url, jobInfo, "application/json")

	//response to the user
	if err != nil {
		return openapi.Response(http.StatusInternalServerError, nil), fmt.Errorf("submit new job request failed")
	}

	if code == http.StatusMultiStatus {
		resp := map[string]interface{}{}
		err = util.ByteToStruct(responseBody, &resp)
		if err != nil {
			zap.S().Errorf("error sending out mutlistatus response %v", err)
		}
		return openapi.Response(http.StatusMultiStatus, resp), nil
	}

	//everything went well and response is a job id
	resp := map[string]string{}
	err = util.ByteToStruct(responseBody, &resp)
	// TODO: simply printing the error doesn't look correct; rethink this again
	if err != nil {
		zap.S().Errorf("error sending out response %v", err)
	}

	return openapi.Response(http.StatusCreated, resp), nil
}

// UpdateJob - Update job by id.
func (s *JobApiService) UpdateJob(ctx context.Context, user string, jobId string, jobInfo openapi.JobInfo) (openapi.ImplResponse, error) {
	// TODO - update UpdateJobEndPoint with the required logic for this service method.
	// Add api_job_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation
	// when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return openapi.Response(http.StatusNotImplemented, nil), fmt.Errorf("UpdateJobEndPoint method not implemented")
}

// ChangeJobSchema - Change the schema for the given job
func (s *JobApiService) ChangeJobSchema(ctx context.Context, user string, jobId string, schemaId string,
	designId string) (openapi.ImplResponse, error) {
	//TODO input validation
	zap.S().Debugf("Change design schema for the given jobId: %s | schemdId: %s | designId: %s", jobId, schemaId, designId)

	//create controller request
	uriMap := map[string]string{
		"user":     user,
		"jobId":    jobId,
		"schemaId": schemaId,
		"designId": designId,
	}

	url := restapi.CreateURL(Host, Port, restapi.ChangeJobSchemaEndPoint, uriMap)

	//send get request
	_, _, err := restapi.HTTPPost(url, nil, "application/json")

	//response to the user
	if err != nil {
		errMsg := "error while changing the design schema for the given job"
		return openapi.Response(http.StatusInternalServerError, nil), fmt.Errorf(errMsg)
	}
	return openapi.Response(http.StatusOK, nil), err
}
