/*
 * Fledge REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"context"
	"errors"
	"net/http"
	"os"

	"wwwin-github.cisco.com/eti/fledge/pkg/openapi"
)

// DesignCodesApiService is a service that implents the logic for the DesignCodesApiServicer
// This service should implement the business logic for every endpoint for the DesignCodesApi API.
// Include any external packages or services that will be required by this service.
type DesignCodesApiService struct {
}

// NewDesignCodesApiService creates a default api service
func NewDesignCodesApiService() openapi.DesignCodesApiServicer {
	return &DesignCodesApiService{}
}

// CreateDesignCode - Update a design doce
func (s *DesignCodesApiService) CreateDesignCode(ctx context.Context, user string, designId string,
	body *os.File) (openapi.ImplResponse, error) {
	// TODO - update CreateDesignCode with the required logic for this service method.
	// Add api_design_codes_service.go to the .openapi-generator-ignore to avoid overwriting this service
	// implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	//return Response(201, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return openapi.Response(http.StatusNotImplemented, nil), errors.New("CreateDesignCode method not implemented")
}

// GetDesignCode - Get a zipped design code file owned by user
func (s *DesignCodesApiService) GetDesignCode(ctx context.Context, user string, designId string,
	version string) (openapi.ImplResponse, error) {
	// TODO - update GetDesignCode with the required logic for this service method.
	// Add api_design_codes_service.go to the .openapi-generator-ignore to avoid overwriting this service
	// implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	//return Response(200, *os.File{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return openapi.Response(http.StatusNotImplemented, nil), errors.New("GetDesignCode method not implemented")
}

// UpdateDesignCode - Update a design doce
func (s *DesignCodesApiService) UpdateDesignCode(ctx context.Context, user string, designId string, version string,
	body *os.File) (openapi.ImplResponse, error) {
	// TODO - update UpdateDesignCode with the required logic for this service method.
	// Add api_design_codes_service.go to the .openapi-generator-ignore to avoid overwriting this service
	// implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return openapi.Response(http.StatusNotImplemented, nil), errors.New("UpdateDesignCode method not implemented")
}
