version: '3'
services:

  database:
    image: 'mongo'
    container_name: 'fledge-db'
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

  notifier:
    image: 'fledge'
    container_name: 'fledge-notifier'
    command: /usr/bin/notifier
    ports:
      - '10101:10101'
    build:
      context: ../
      dockerfile: ./build/Dockerfile.dev

  controller:
    image: 'fledge'
    container_name: 'fledge-controller'
    # The ""sleep 5"" is to mitigate failure to connect mongodb
    # if controler comes up before mongodb
    # TODO: refactor controller code to retry connection in case of disconnection
    command: >
      bash -c "sleep 5 && /usr/bin/controller"
    ports:
      - '10102:10102'
    volumes:
      - ${PWD}/controller.yaml:/etc/fledge/controller.yaml
    depends_on: ['database', 'notifier']

  apiserver:
    image: 'fledge'
    container_name: 'fledge-apiserver'
    command: /usr/bin/apiserver --controller fledge-controller:10102
    ports:
      - '10100:10100'
    depends_on: ['controller']

  fledgelet1:
    image: 'fledge'
    container_name: 'fledgelet1'
    # NOTE: update FLEDGE_AGENT_ID based on the task
    #       when a job is first executed, it will fail.
    #       log into controller container and check its logs to identify agent IDs
    #       docker exec -it fledge-controller bash
    #       cat /var/log/fledge/controller.log | grep "Creating task for agent"
    #       use the IDs returned from the above grep search
    environment:
      FLEDGE_AGENT_ID: 899f61f470583dd22314da1e17214092338fbffa
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10103:10103'
    depends_on: ['apiserver', 'notifier']

  fledgelet2:
    image: 'fledge'
    container_name: 'fledgelet2'
    # NOTE: update FLEDGE_AGENT_ID based on the task
    environment:
      FLEDGE_AGENT_ID: a65f8555a1d3a5bea0fe2861c11ae98b2520790f
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10104:10104'
    depends_on: ['apiserver', 'notifier']

  fledgelet3:
    image: 'fledge'
    container_name: 'fledgelet3'
    # NOTE: update FLEDGE_AGENT_ID based on the task
    environment:
      FLEDGE_AGENT_ID: bcbefeadacbc9b58747600ce573f18841edc3460
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10105:10105'
    depends_on: ['apiserver', 'notifier']
