version: '3'
services:

  database:
    image: 'mongo'
    container_name: 'fledge-db'
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

  notifier:
    image: 'fledge'
    container_name: 'fledge-notifier'
    command: /usr/bin/notifier
    ports:
      - '10101:10101'
    build:
      context: ../
      dockerfile: ./build/Dockerfile.dev

  controller:
    image: 'fledge'
    container_name: 'fledge-controller'
    # The ""sleep 5"" is to mitigate failure to connect mongodb
    # if controler comes up before mongodb
    # TODO: refactor controller code to retry connection in case of disconnection
    command: >
      bash -c "sleep 5 &&
      /usr/bin/controller
      --db mongodb://fledge-db:27017
      --notifier fledge-notifier:10101
      --platform docker"
    ports:
      - '10102:10102'
    depends_on: ['database', 'notifier']

  apiserver:
    image: 'fledge'
    container_name: 'fledge-apiserver'
    command: /usr/bin/apiserver --controller fledge-controller:10102
    ports:
      - '10100:10100'
    depends_on: ['controller']

  fledgelet1:
    image: 'fledge'
    container_name: 'fledgelet1'
    # NOTE: update FLEDGE_AGENT_ID based on the task
    #       when a job is first executed, it will fail.
    #       log into controller container and check its logs to identify agent IDs
    #       docker exec -it fledge-controller bash
    #       cat /var/log/fledge/controller.log | grep "Creating task for agent"
    #       use the IDs returned from the above grep search
    environment:
      FLEDGE_AGENT_ID: a07f656a6cc4aa5618ff79f3a0af3a6ba46ce957
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10103:10103'
    depends_on: ['apiserver', 'notifier']

  fledgelet2:
    image: 'fledge'
    container_name: 'fledgelet2'
    # NOTE: update FLEDGE_AGENT_ID based on the task
    environment:
      FLEDGE_AGENT_ID: 792f51acfcba8b3e6a068e3f761b0a931abeabdb
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10104:10104'
    depends_on: ['apiserver', 'notifier']

  fledgelet3:
    image: 'fledge'
    container_name: 'fledgelet3'
    # NOTE: update FLEDGE_AGENT_ID based on the task
    environment:
      FLEDGE_AGENT_ID: a2f0520404d18030b34a81352b33f2d625e7e1bc
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10105:10105'
    depends_on: ['apiserver', 'notifier']
