---
version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow

  mlflow:
    image: 'adacotechjp/mlflow:1.21.0'
    container_name: 'mlflow'
    entrypoint: ""
    command: >
      bash -c "mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow
      --default-artifact-root file:./mlruns
      --host 0.0.0.0"
    ports:
      - '5000:5000'
    depends_on: ['postgres']

  database:
    image: 'mongo'
    container_name: 'fledge-db'
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

  notifier:
    image: 'fledge'
    container_name: 'fledge-notifier'
    command: /usr/bin/notifier
    ports:
      - '10101:10101'
    build:
      context: ../
      dockerfile: ./build/Dockerfile.dev

  controller:
    image: 'fledge'
    container_name: 'fledge-controller'
    # The ""sleep 5"" is to mitigate failure to connect mongodb
    # if controler comes up before mongodb
    # TODO: refactor controller code to retry connection in case of disconnection
    command: >
      bash -c "sleep 5 && /usr/bin/controller"
    ports:
      - '10102:10102'
    volumes:
      - ${PWD}/controller.yaml:/etc/fledge/controller.yaml
    depends_on: ['database', 'notifier']

  apiserver:
    image: 'fledge'
    container_name: 'fledge-apiserver'
    command: /usr/bin/apiserver --controller fledge-controller:10102
    ports:
      - '10100:10100'
    depends_on: ['controller']

  fledgelet1:
    image: 'fledge'
    container_name: 'fledgelet1'
    volumes:
      - ./mlruns:/mlruns
      - ../:/src/fledge
    # NOTE: update FLEDGE_AGENT_ID based on the task
    #       when a job is first executed, it will fail.
    #       log into controller container and check its logs to identify agent IDs
    #       docker exec -it fledge-controller bash
    #       cat /var/log/fledge/controller.log | grep "Creating task for agent"
    #       use the IDs returned from the above grep search
    environment:
      FLEDGE_AGENT_ID: 9f1cae384620dbc68ae4070fe5a8a610f3ea456f
      LOG_LEVEL: DEBUG
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10103:10103'
    depends_on: ['apiserver', 'notifier']

  fledgelet2:
    image: 'fledge'
    container_name: 'fledgelet2'
    volumes:
      - ./mlruns:/mlruns
      - ../:/src/fledge
    # NOTE: update FLEDGE_AGENT_ID based on the task
    environment:
      FLEDGE_AGENT_ID: d36a233e2e85d2d479470f86e61592395c02306f
      LOG_LEVEL: DEBUG
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10104:10104'
    depends_on: ['apiserver', 'notifier']

  fledgelet3:
    image: 'fledge'
    container_name: 'fledgelet3'
    volumes:
      - ./mlruns:/mlruns
      - ../:/src/fledge
    # NOTE: update FLEDGE_AGENT_ID based on the task
    environment:
      FLEDGE_AGENT_ID: 536b8978f8b8aa90576cdb9f80dceaa809c53852
      LOG_LEVEL: DEBUG
    command: /usr/bin/fledgelet --apiserver fledge-apiserver:10100 --notifier fledge-notifier:10101
    ports:
      - '10105:10105'
    depends_on: ['apiserver', 'notifier']
