Vagrant.configure("2") do |config|
  config.vm.box = "myungjin-lee/fledge"

  config.vm.define "fledge"
  config.vm.hostname = "fledge"

  # 8888: access to vernemq UI
  config.vm.network "forwarded_port", guest: 8888, host: 8880,
    auto_correct: true

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../", "/fledge"
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "fledge"
    vb.memory = 2048
    vb.cpus = 2
  end
end
