---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-controller
  namespace: {{ .Values.servicename }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}-controller
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}-controller
    spec:
      containers:
        - args: []
          command: ["/usr/bin/controller"]
          image: {{ .Values.imageName }}:latest
          imagePullPolicy: IfNotPresent
          name: {{ .Values.servicename }}-controller
          ports:
            - containerPort: {{ .Values.componentPorts.controller }}
          volumeMounts:
            - mountPath: /etc/flame/controller.yaml
              name: config-volume
              subPath: controller.yaml
      serviceAccountName: controller
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-controller-configmap
