---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-configmap
  namespace: {{ .Values.servicename }}
data:
  controller.yaml: |
    ---
    brokers:
      - sort: mqtt
        host: mqtt.eclipseprojects.io
    db: mongodb://fledge-db:27017
    notifier: fledge-notifier:10101
    platform: k8s
    registry:
      sort: mlflow
      uri: http://mlflow:5000
