---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-configmap
  namespace: {{ .Values.servicename }}
data:
  controller.yaml: |
    ---
    brokers:
      - sort: mqtt
        host: mosquitto
    db: mongodb://fledge-mongodb-headless:27017/?replicaSet=rs0
    notifier: fledge-notifier:10101
    platform: k8s
    registry:
      sort: mlflow
      uri: http://mlflow:5000
