---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}-db
  namespace: {{ .Values.servicename }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.servicename }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.servicename }}-db
    spec:
      containers:
        - image: mongo
          imagePullPolicy: IfNotPresent
          name: {{ .Values.servicename }}-db
          ports:
            - containerPort: 27017
            - containerPort: 27018
            - containerPort: 27019
