---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.servicename }}-db
  name: {{ .Values.servicename }}-db
  namespace: {{ .Values.servicename }}
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    - name: "27018"
      port: 27018
      targetPort: 27018
    - name: "27019"
      port: 27019
      targetPort: 27019
  selector:
    app: {{ .Values.servicename }}-db
  type: LoadBalancer
