apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployer
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployer
    spec:
      containers:
        - args: []
          command: ["/usr/bin/deployer"]
          image: {{ .Values.imageName }}:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          name: {{ .Release.Name }}-deployer
