---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mlflow
    tier: backend
  name: mlflow
  namespace: {{ .Values.servicename }}
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: mlflow
  type: LoadBalancer
