---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: {{ .Values.servicename }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - args:
            - "mlflow server --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow --default-artifact-root file:./mlruns --host 0.0.0.0"
          command: ["bash", "-c"]
          image: adacotechjp/mlflow:1.21.0
          name: mlflow
          ports:
            - containerPort: 5000
      restartPolicy: Always
