---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mosquitto-configmap
  namespace: {{ .Values.servicename }}
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
