---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: postgres
    tier: backend
  name: postgres
  namespace: {{ .Values.servicename }}
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
