---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.servicename }}

spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: mlflow
            - name: POSTGRES_PASSWORD
              value: mlflow
            - name: POSTGRES_USER
              value: mlflow
          image: postgres
          name: postgres
          ports:
            - containerPort: 5432
      restartPolicy: Always
